import { describe,expect,it } from 'vitest'; import { CompatibilityDataSource,DirectProximity,GeographyCompatibilityEngine,normalizeLgaPair,SharedHub } from './compatibility.js';
class FixtureSource implements CompatibilityDataSource { existing=new Set(['A','B','C','D','E']); pairs=new Map<string,DirectProximity>(); hubs=new Map<string,SharedHub[]>(); key(a:string,b:string){return normalizeLgaPair(a,b).join(':')} lgasExist(ids:readonly[string,string]){return Promise.resolve(ids.every(x=>this.existing.has(x)))} directPair(a:string,b:string){return Promise.resolve(this.pairs.get(this.key(a,b))??null)} sharedHubs(a:string,b:string){return Promise.resolve(this.hubs.get(this.key(a,b))??[])} }
describe('GeographyCompatibilityEngine',()=>{
  it('same LGA is compatible without a data lookup',async()=>{const s=new FixtureSource();s.existing.clear();expect(await new GeographyCompatibilityEngine(s).evaluate('A','A')).toEqual({compatible:true,relationship:'SAME_LGA',estimatedRoadMinutes:0,commonHubId:null,reason:'SAME_LGA'})});
  it.each([45,60])('%i direct minutes is nearby',async minutes=>{const s=new FixtureSource();s.pairs.set('A:B',{estimatedRoadMinutes:minutes});expect((await new GeographyCompatibilityEngine(s).evaluate('A','B')).relationship).toBe('NEARBY_LGA')});
  it('61 minutes is not directly compatible',async()=>{const s=new FixtureSource();s.pairs.set('A:B',{estimatedRoadMinutes:61});expect(await new GeographyCompatibilityEngine(s).evaluate('A','B')).toMatchObject({compatible:false,relationship:'NOT_COMPATIBLE',reason:'OVER_60_MINUTES'})});
  it('uses a common hub when both legs are within 60 minutes',async()=>{const s=new FixtureSource();s.hubs.set('A:B',[{hubId:'H',hubName:'Owerri',minutesA:40,minutesB:55}]);expect(await new GeographyCompatibilityEngine(s).evaluate('A','B')).toMatchObject({compatible:true,relationship:'COMMON_HUB',estimatedRoadMinutes:55,commonHubId:'H'})});
  it('rejects a common hub when one leg is 75 minutes',async()=>{const s=new FixtureSource();s.hubs.set('A:B',[{hubId:'H',hubName:'Owerri',minutesA:40,minutesB:75}]);expect(await new GeographyCompatibilityEngine(s).evaluate('A','B')).toMatchObject({compatible:false,relationship:'NOT_COMPATIBLE'})});
  it('returns UNKNOWN when no evidence exists',async()=>{const s=new FixtureSource();expect(await new GeographyCompatibilityEngine(s).evaluate('A','B')).toMatchObject({compatible:false,relationship:'UNKNOWN',reason:'INSUFFICIENT_DATA'})});
  it('returns UNKNOWN for an invalid LGA',async()=>{const s=new FixtureSource();expect((await new GeographyCompatibilityEngine(s).evaluate('A','Z')).relationship).toBe('UNKNOWN')});
  it('is symmetric for reversed inputs',async()=>{const s=new FixtureSource();s.pairs.set('A:B',{estimatedRoadMinutes:38,commonHubId:'H'});const engine=new GeographyCompatibilityEngine(s);expect(await engine.evaluate('A','B')).toEqual(await engine.evaluate('B','A'))});
  it('prefers direct proximity over a common hub',async()=>{const s=new FixtureSource();s.pairs.set('A:B',{estimatedRoadMinutes:50});s.hubs.set('A:B',[{hubId:'H',hubName:'Hub',minutesA:10,minutesB:10}]);expect((await new GeographyCompatibilityEngine(s).evaluate('A','B')).relationship).toBe('NEARBY_LGA')});
});
