import { describe,expect,it } from 'vitest';
import { departureCompatibility,evaluatePair,MatchPlan,sharedDate,transportCompatibility } from './matching.compatibility.js';
const base:MatchPlan={id:'a',userId:'a',destinationCampId:'camp',originLgaId:'lga-a',originTownId:null,intendedTravelDate:'2026-09-14',dateFlexibilityDays:0,departureWindow:'MORNING',transportMode:'COMMERCIAL_BUS',transportFlexible:false,nearbyMatchingEnabled:true,groupPreference:'ANY_VERIFIED_PCM',createdAt:new Date(0)};
const geo=(relationship:'NEARBY_LGA'|'COMMON_HUB'|'NOT_COMPATIBLE'|'UNKNOWN',minutes:number|null=null)=>({evaluate:async()=>({compatible:['NEARBY_LGA','COMMON_HUB'].includes(relationship),relationship,estimatedRoadMinutes:minutes,commonHubId:relationship==='COMMON_HUB'?'hub':null,reason:'INSUFFICIENT_DATA' as const})});
describe('matching v1 compatibility',()=>{
  it('rejects self matching and different destination camps',async()=>{expect((await evaluatePair(base,base,geo('UNKNOWN'))).kind).toBe('INCOMPATIBLE');expect((await evaluatePair(base,{...base,id:'b',userId:'b',destinationCampId:'other'},geo('UNKNOWN'))).kind).toBe('INCOMPATIBLE')});
  it('ranks same Town above same LGA',async()=>{const town=await evaluatePair({...base,originTownId:'town'},{...base,id:'b',userId:'b',originTownId:'town'},geo('UNKNOWN'));const lga=await evaluatePair(base,{...base,id:'b',userId:'b'},geo('UNKNOWN'));expect(town.originRelationship).toBe('SAME_TOWN');expect(town.score).toBeGreaterThan(lga.score)});
  it.each([[30,true],[60,true],[61,false]])('applies the locked nearby threshold at %i minutes',async(minutes,compatible)=>{const result=await evaluatePair(base,{...base,id:'b',userId:'b',originLgaId:'lga-b'},geo(minutes<=60?'NEARBY_LGA':'NOT_COMPATIBLE',minutes));expect(result.kind==='DIRECT').toBe(compatible)});
  it('supports a shared hub and retains its id',async()=>{const result=await evaluatePair(base,{...base,id:'b',userId:'b',originLgaId:'lga-b'},geo('COMMON_HUB',50));expect(result.kind).toBe('DIRECT');expect(result.originHubId).toBe('hub')});
  it('does not guess UNKNOWN geography or override nearby opt-out',async()=>{expect((await evaluatePair(base,{...base,id:'b',userId:'b',originLgaId:'lga-b'},geo('UNKNOWN'))).kind).toBe('INCOMPATIBLE');expect((await evaluatePair(base,{...base,id:'b',userId:'b',originLgaId:'lga-b',nearbyMatchingEnabled:false},geo('NEARBY_LGA',38))).kind).toBe('INCOMPATIBLE')});
  it('finds deterministic ±1 and ±2 date intersections',()=>{expect(sharedDate({...base,dateFlexibilityDays:1},{...base,intendedTravelDate:'2026-09-15'})).toBe('2026-09-15');expect(sharedDate({...base,dateFlexibilityDays:2},{...base,intendedTravelDate:'2026-09-16'})).toBe('2026-09-16');expect(sharedDate(base,{...base,intendedTravelDate:'2026-09-15'})).toBeNull()});
  it('treats overlapping date flexibility as a direct match',async()=>{const result=await evaluatePair({...base,dateFlexibilityDays:2},{...base,id:'b',userId:'b',intendedTravelDate:'2026-09-15',dateFlexibilityDays:2},geo('UNKNOWN'));expect(result.kind).toBe('DIRECT');expect(result.proposedTravelDate).toBe('2026-09-14');expect(result.offerType).toBeUndefined()});
  it('handles same, adjacent, flexible, and distant departure windows',()=>{expect(departureCompatibility('MORNING','MORNING').score).toBe(20);expect(departureCompatibility('EARLY_MORNING','MORNING').score).toBe(14);expect(departureCompatibility('MORNING','LATE_MORNING').compatible).toBe(true);expect(departureCompatibility('FLEXIBLE','MORNING').window).toBe('MORNING');expect(departureCompatibility('EARLY_MORNING','AFTERNOON').compatible).toBe(false)});
  it('turns a major departure change into an offer',async()=>{const result=await evaluatePair(base,{...base,id:'b',userId:'b',departureWindow:'AFTERNOON'},geo('UNKNOWN'));expect(result.kind).toBe('ALTERNATIVE');expect(result.offerType).toBe('ALTERNATIVE_TIME')});
  it('handles transport without silent changes',()=>{expect(transportCompatibility(base,{...base,transportMode:'COMMERCIAL_BUS'}).kind).toBe('DIRECT');expect(transportCompatibility(base,{...base,transportMode:'UNDECIDED'}).kind).toBe('DIRECT');expect(transportCompatibility(base,{...base,transportMode:'FLIGHT'}).kind).toBe('INCOMPATIBLE');expect(transportCompatibility({...base,transportFlexible:true},{...base,transportMode:'TRAIN'}).kind).toBe('DIRECT');expect(transportCompatibility(base,{...base,transportMode:'PRIVATE_VEHICLE'}).kind).toBe('INCOMPATIBLE')});
});
