import { afterAll,beforeAll,describe,expect,it } from 'vitest'; import { and,eq,inArray,ne } from 'drizzle-orm'; import { db,pool } from '../src/db/database.js'; import { auditLogs,domainOutbox,nyscIntakes,orientationCamps,pcmVerifications,states,towns,travelPlans,users } from '../src/db/schema.js'; import { GeographyService } from '../src/geography/geography.service.js'; import { MatchingService } from '../src/matching/matching.service.js'; import { TravelPlanService } from '../src/travel-plans/travel-plan.service.js'; import { expireTravelPlans } from '../src/travel-plans/expire.js';
const enabled=Boolean(process.env.TEST_DATABASE_URL||process.env.DATABASE_URL?.includes('kopa_padi_phase3'));const suite=enabled?describe:describe.skip;const ids={grace:crypto.randomUUID(),victor:crypto.randomUUID(),admin:crypto.randomUUID(),unverified:crypto.randomUUID()};let verificationId='';let destinationId='';let planId='';let wrongTownId='';const service=new TravelPlanService(new MatchingService(new GeographyService()));const input={originStateId:'NG017',originLgaId:'NG017025',originTownId:null,intendedTravelDate:'2099-09-14',dateFlexibilityDays:1 as const,departureWindow:'MORNING' as const,transportMode:'COMMERCIAL_BUS' as const,transportFlexible:false,nearbyMatchingEnabled:true,groupPreference:'ANY_VERIFIED_PCM' as const};
suite.sequential('Travel Plan PostgreSQL integration',()=>{
beforeAll(async()=>{await db.insert(users).values([{id:ids.grace,name:'Grace',email:`grace-${ids.grace}@test.invalid`,emailVerified:true},{id:ids.victor,name:'Victor',email:`victor-${ids.victor}@test.invalid`,emailVerified:true},{id:ids.admin,name:'Admin',email:`admin-${ids.admin}@test.invalid`,emailVerified:true,role:'ADMIN'},{id:ids.unverified,name:'Unverified',email:`unverified-${ids.unverified}@test.invalid`,emailVerified:true}]);const[intake]=await db.select().from(nyscIntakes).limit(1);const[camp]=await db.select().from(orientationCamps).limit(1);const[wrongTown]=await db.select().from(towns).where(ne(towns.lgaId,input.originLgaId)).limit(1);wrongTownId=wrongTown.id;destinationId=camp.id;verificationId=crypto.randomUUID();await db.insert(pcmVerifications).values({id:verificationId,userId:ids.grace,nyscIntakeId:intake.id,orientationCampId:camp.id,status:'VERIFIED',submittedAt:new Date(),reviewedAt:new Date(),verifiedAt:new Date(),reviewedBy:ids.admin})});
afterAll(async()=>{const userIds=Object.values(ids);await db.delete(domainOutbox).where(eq(domainOutbox.aggregateType,'TRAVEL_PLAN'));await db.delete(auditLogs).where(inArray(auditLogs.actorUserId,userIds));await db.delete(travelPlans).where(inArray(travelPlans.userId,userIds));await db.delete(pcmVerifications).where(inArray(pcmVerifications.userId,userIds));await db.delete(users).where(inArray(users.id,userIds));await pool.end()});
it('rejects an unverified user',async()=>{await expect(service.create(ids.unverified,input)).rejects.toThrow()});
it('allows only one of two concurrent creates and derives verified destination',async()=>{const results=await Promise.allSettled([service.create(ids.grace,input),service.create(ids.grace,input)]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(results.filter(x=>x.status==='rejected')).toHaveLength(1);const active=await service.active(ids.grace);expect(active?.plan.destinationCampId).toBe(destinationId);expect(active?.plan.pcmVerificationId).toBe(verificationId);expect(active?.plan.status).toBe('SEARCHING');planId=active!.plan.id;const events=await db.select().from(domainOutbox).where(and(eq(domainOutbox.aggregateId,planId),eq(domainOutbox.eventType,'TravelPlanCreated')));expect(events).toHaveLength(1)});
it('does not expose a plan through another owner',async()=>{await expect(service.ownedDetail(ids.victor,planId)).rejects.toThrow('Travel Plan not found')});
it('rejects mismatched State/LGA and LGA/Town edits without changing the plan',async()=>{await expect(service.update(ids.grace,planId,{...input,originStateId:'NG014'})).rejects.toThrow('LGA does not belong');await expect(service.update(ids.grace,planId,{...input,originTownId:wrongTownId})).rejects.toThrow('Town does not belong');const unchanged=await service.ownedDetail(ids.grace,planId);expect(unchanged.plan.originStateId).toBe(input.originStateId);expect(unchanged.plan.originTownId).toBeNull()});
it('stores nearby matching disabled and emits one update event',async()=>{const updated=await service.update(ids.grace,planId,{...input,departureWindow:'AFTERNOON',nearbyMatchingEnabled:false});expect(updated.plan.nearbyMatchingEnabled).toBe(false);expect(updated.plan.departureWindow).toBe('AFTERNOON');expect(await db.select().from(domainOutbox).where(and(eq(domainOutbox.aggregateId,planId),eq(domainOutbox.eventType,'TravelPlanUpdated')))).toHaveLength(1)});
it('cancels idempotently, emits one event, and permits recreation without a Town',async()=>{await service.cancel(ids.grace,planId,'TRAVEL_NO_LONGER_NEEDED');await service.cancel(ids.grace,planId,'OTHER');expect(await db.select().from(domainOutbox).where(and(eq(domainOutbox.aggregateId,planId),eq(domainOutbox.eventType,'TravelPlanCancelled')))).toHaveLength(1);const next=await service.create(ids.grace,{...input,nearbyMatchingEnabled:false});expect(next.plan.originTownId).toBeNull();expect(next.plan.status).toBe('SEARCHING');planId=next.plan.id});
it('expires stale plans once and emits one expiry event',async()=>{await db.update(travelPlans).set({expiresAt:new Date('2020-01-01')}).where(eq(travelPlans.id,planId));expect(await expireTravelPlans(new Date())).toHaveLength(1);expect(await expireTravelPlans(new Date())).toHaveLength(0);expect(await db.select().from(domainOutbox).where(and(eq(domainOutbox.aggregateId,planId),eq(domainOutbox.eventType,'TravelPlanExpired')))).toHaveLength(1)});
});
