import{BadRequestException,ConflictException,ForbiddenException,Injectable,NotFoundException}from'@nestjs/common';import{and,asc,count,desc,eq,inArray,isNotNull,lte,or,sql}from'drizzle-orm';import{db}from'../db/database.js';import{auditLogs,journeyGuideFeedback,journeyGuideSources,journeyGuides,journeyLegs,journeys,orientationCamps,travelHubLgas,travelPlans}from'../db/schema.js';import{assertGuideTransition,chooseMostSpecific,staleBefore}from'./journey-guide.domain.js';
@Injectable()export class JourneyGuideResolver{
 async resolve(input:{originStateId:string;originLgaId:string;originTownId:string|null;destinationCampId:string}){
  const hubs=await db.select({id:travelHubLgas.travelHubId}).from(travelHubLgas).where(and(eq(travelHubLgas.lgaId,input.originLgaId),eq(travelHubLgas.isPrimary,true)));
  const rows=await db.select().from(journeyGuides).where(and(eq(journeyGuides.destinationCampId,input.destinationCampId),eq(journeyGuides.status,'PUBLISHED'),or(input.originTownId?and(eq(journeyGuides.originScopeType,'TOWN'),eq(journeyGuides.originTownId,input.originTownId)):undefined,and(eq(journeyGuides.originScopeType,'LGA'),eq(journeyGuides.originLgaId,input.originLgaId)),hubs.length?and(eq(journeyGuides.originScopeType,'TRAVEL_HUB'),inArray(journeyGuides.originHubId,hubs.map(h=>h.id))):undefined,and(eq(journeyGuides.originScopeType,'STATE_AREA'),eq(journeyGuides.originStateId,input.originStateId)))));const guide=chooseMostSpecific(rows);return guide?{guide,matchScope:guide.originScopeType,confidence:guide.confidenceLevel}:{status:'NO_GUIDE_AVAILABLE' as const};
 }}
@Injectable()export class JourneyGuideService{
 constructor(private readonly resolver:JourneyGuideResolver){}
 private async full(id:string,publishedOnly=false){const[guide]=await db.select().from(journeyGuides).where(and(eq(journeyGuides.id,id),publishedOnly?eq(journeyGuides.status,'PUBLISHED'):undefined)).limit(1);if(!guide)throw new NotFoundException('Journey guide not found');const[legs,sources,camp]=await Promise.all([db.select().from(journeyLegs).where(eq(journeyLegs.journeyGuideId,id)).orderBy(asc(journeyLegs.sequenceNumber)),db.select().from(journeyGuideSources).where(eq(journeyGuideSources.journeyGuideId,id)),db.select({name:orientationCamps.campName,address:orientationCamps.officialAddress,state:orientationCamps.stateName}).from(orientationCamps).where(eq(orientationCamps.id,guide.destinationCampId)).limit(1).then(r=>r[0])]);return{guide,legs,sources,destination:{...camp,informationType:'OFFICIAL_CAMP_INFORMATION'},guidanceType:'REVIEWED_PLATFORM_GUIDANCE'}}
 async recommended(userId:string){const[plan]=await db.select().from(travelPlans).where(and(eq(travelPlans.userId,userId),inArray(travelPlans.status,['SEARCHING','IN_CIRCLE','LOCKED','IN_JOURNEY','COMPLETED']))).orderBy(desc(travelPlans.updatedAt)).limit(1);if(!plan)throw new NotFoundException('Travel Plan not found');const result=await this.resolver.resolve({originStateId:plan.originStateId,originLgaId:plan.originLgaId,originTownId:plan.originTownId,destinationCampId:plan.destinationCampId});if('status'in result)return{...result,destinationCampId:plan.destinationCampId};return{matchScope:result.matchScope,confidence:result.confidence,...await this.full(result.guide.id,true)}}
 read(id:string){return this.full(id,true)}
 list(status?:any){return db.select().from(journeyGuides).where(status?eq(journeyGuides.status,status):undefined).orderBy(desc(journeyGuides.updatedAt))}
 adminRead(id:string){return this.full(id)}
 private validate(input:any){const ids=input.legs.map((l:any)=>l.sequenceNumber);if(!ids.length)throw new BadRequestException('At least one leg is required');if(new Set(ids).size!==ids.length||[...ids].sort((a,b)=>a-b).some((n,i)=>n!==i+1))throw new BadRequestException('Leg sequence must be contiguous from 1');if(!input.sources.length)throw new BadRequestException('At least one traceable source is required');const scope:any={TOWN:'originTownId',LGA:'originLgaId',TRAVEL_HUB:'originHubId',STATE_AREA:'originStateId'};if(!input[scope[input.originScopeType]])throw new BadRequestException('Origin scope reference is required')}
 async create(actor:string,input:any){this.validate(input);return db.transaction(async(tx:any)=>{const{legs,sources,...guideData}=input;const[guide]=await tx.insert(journeyGuides).values({...guideData,createdBy:actor}).returning();await this.replaceChildren(tx,guide.id,legs,sources);await this.audit(tx,actor,'JOURNEY_GUIDE_CREATED',guide);return this.full(guide.id)})}
 async edit(actor:string,id:string,input:any){this.validate(input);return db.transaction(async(tx:any)=>{const[current]=await tx.select().from(journeyGuides).where(eq(journeyGuides.id,id)).limit(1);if(!current)throw new NotFoundException('Journey guide not found');if(!['DRAFT','NEEDS_REVIEW'].includes(current.status))throw new ConflictException('Only draft or needs-review guides can be edited');const{legs,sources,...guideData}=input;const[next]=current.status==='NEEDS_REVIEW'?await tx.insert(journeyGuides).values({...guideData,version:current.version+1,status:'DRAFT',createdBy:actor}).returning():await tx.update(journeyGuides).set({...guideData,updatedAt:new Date()}).where(eq(journeyGuides.id,id)).returning();await this.replaceChildren(tx,next.id,legs,sources);await this.audit(tx,actor,'JOURNEY_GUIDE_EDITED',next);return this.full(next.id)})}
 private async replaceChildren(tx:any,id:string,legs:any[],sources:any[]){await tx.delete(journeyGuideSources).where(eq(journeyGuideSources.journeyGuideId,id));await tx.delete(journeyLegs).where(eq(journeyLegs.journeyGuideId,id));const made=await tx.insert(journeyLegs).values(legs.map(l=>({...l,estimatedDistanceKm:l.estimatedDistanceKm?String(l.estimatedDistanceKm):null,journeyGuideId:id}))).returning();await tx.insert(journeyGuideSources).values(sources.map(s=>{const{journeyLegSequence,...rest}=s;return{...rest,journeyGuideId:id,journeyLegId:journeyLegSequence?made.find((l:any)=>l.sequenceNumber===journeyLegSequence)?.id:null,sourceDate:rest.sourceDate??null,reviewedAt:rest.reviewedAt?new Date(rest.reviewedAt):null}}))}
 async transition(actor:string,id:string,to:'UNDER_REVIEW'|'PUBLISHED'|'NEEDS_REVIEW'|'RETIRED'){return db.transaction(async(tx:any)=>{const[g]=await tx.select().from(journeyGuides).where(eq(journeyGuides.id,id)).limit(1);if(!g)throw new NotFoundException('Journey guide not found');assertGuideTransition(g.status,to);if(to==='PUBLISHED'){const[legs]=await tx.select({n:count()}).from(journeyLegs).where(eq(journeyLegs.journeyGuideId,id));const[sources]=await tx.select({n:count()}).from(journeyGuideSources).where(eq(journeyGuideSources.journeyGuideId,id));if(!Number(legs.n)||!Number(sources.n))throw new BadRequestException('Reviewed legs and sources are required')}const now=new Date();const[row]=await tx.update(journeyGuides).set({status:to,reviewedBy:to==='PUBLISHED'?actor:g.reviewedBy,lastReviewedAt:to==='PUBLISHED'?now:g.lastReviewedAt,publishedAt:to==='PUBLISHED'?now:g.publishedAt,retiredAt:to==='RETIRED'?now:null,updatedAt:now}).where(eq(journeyGuides.id,id)).returning();const action:any=to==='UNDER_REVIEW'?'JOURNEY_GUIDE_SUBMITTED_FOR_REVIEW':to==='PUBLISHED'?'JOURNEY_GUIDE_PUBLISHED':to==='RETIRED'?'JOURNEY_GUIDE_RETIRED':'JOURNEY_GUIDE_EDITED';await this.audit(tx,actor,action,row);return row})}
 async feedback(userId:string,id:string,input:any){const[j]=await db.select().from(journeys).where(and(eq(journeys.userId,userId),eq(journeys.journeyGuideId,id),eq(journeys.status,'COMPLETED'),isNotNull(journeys.journeyGuideVersion))).orderBy(desc(journeys.completedAt)).limit(1);if(!j)throw new ForbiddenException('Completed Journey using this guide is required');const[row]=await db.insert(journeyGuideFeedback).values({...input,journeyId:j.id,journeyGuideId:id,journeyGuideVersion:j.journeyGuideVersion!,userId}).onConflictDoNothing().returning();if(!row)throw new ConflictException('Feedback already submitted');return{id:row.id,submitted:true}}
 async flagStale(now=new Date()){const rows=await db.update(journeyGuides).set({status:'NEEDS_REVIEW',updatedAt:now}).where(and(eq(journeyGuides.status,'PUBLISHED'),lte(journeyGuides.lastReviewedAt,staleBefore(now)))).returning({id:journeyGuides.id});return{flagged:rows.length}}
 async metrics(){const r=await db.execute(sql`select count(*) filter(where status='PUBLISHED')::int published_guides,count(*) filter(where status='NEEDS_REVIEW')::int guides_needing_review,(select count(*)::int from journey_guide_feedback) feedback_count,(select count(*) filter(where was_useful)::int from journey_guide_feedback) useful_count,(select count(*) filter(where was_accurate in ('YES','MOSTLY'))::int from journey_guide_feedback) accurate_count,(select count(*) filter(where final_connection_accurate='YES')::int from journey_guide_feedback) final_connection_accurate from journey_guide`);return r.rows[0]}
 private audit(tx:any,actor:string,action:any,g:any){return tx.insert(auditLogs).values({actorUserId:actor,action,resourceType:'JOURNEY_GUIDE',resourceId:g.id,metadata:{version:g.version}})}
}
